# Generated by Django 6.1 on 2026-09-03 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name, e.g., Midterm, Final Exam, Quizzes', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight as percentage, e.g., 30.00 for 30%', max_digits=5)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this assessment category')),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_categories', to='academics.subjectassignment')),
            ],
            options={
                'verbose_name': 'assessment category',
                'verbose_name_plural': 'assessment categories',
                'ordering': ['subject_assignment', 'name'],
                'unique_together': {('name', 'subject_assignment')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, help_text="Student's raw score", max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible score for this assessment', max_digits=7)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional teacher remarks for this grade')),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grading.assessmentcategory')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Teacher or staff who recorded this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollment.studentprofile')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['-assessment_category', 'student'],
                'unique_together': {('student', 'assessment_category')},
            },
        ),
    ]
